# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://wedxz@bitbucket.org/vvusu/lnspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'LNMarket' do
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'
pod ‘LNStock'
end

target 'LNMarketTests' do

end

target 'LNMarketUITests' do

end

